package modelo;
// Generated 6/10/2020 07:46:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dias generated by hbm2java
 */
public class Dias  implements java.io.Serializable {


     private int idDia;
     private String combinacionDias;
     private Set horarios = new HashSet(0);

    public Dias() {
    }

	
    public Dias(int idDia, String combinacionDias) {
        this.idDia = idDia;
        this.combinacionDias = combinacionDias;
    }
    public Dias(int idDia, String combinacionDias, Set horarios) {
       this.idDia = idDia;
       this.combinacionDias = combinacionDias;
       this.horarios = horarios;
    }
   
    public int getIdDia() {
        return this.idDia;
    }
    
    public void setIdDia(int idDia) {
        this.idDia = idDia;
    }
    public String getCombinacionDias() {
        return this.combinacionDias;
    }
    
    public void setCombinacionDias(String combinacionDias) {
        this.combinacionDias = combinacionDias;
    }
    public Set getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set horarios) {
        this.horarios = horarios;
    }




}


