package modelo;
// Generated 6/10/2020 07:46:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private HorarioId id;
     private Dias dias;
     private Servicios servicios;
     private Date horaInicio;
     private Date horaFin;

    public Horario() {
    }

    public Horario(HorarioId id, Dias dias, Servicios servicios, Date horaInicio, Date horaFin) {
       this.id = id;
       this.dias = dias;
       this.servicios = servicios;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
    }

    public Horario(HorarioId id, Dias dias, Date horaInicio, Date horaFin) {
        this.id = id;
        this.dias = dias;
        this.horaInicio = horaInicio;
        this.horaFin = horaFin;
    }
    
   
    public HorarioId getId() {
        return this.id;
    }
    
    public void setId(HorarioId id) {
        this.id = id;
    }
    public Dias getDias() {
        return this.dias;
    }
    
    public void setDias(Dias dias) {
        this.dias = dias;
    }
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }




}


