package modelo;
// Generated 6/10/2020 07:46:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Recorridos generated by hbm2java
 */
public class Recorridos  implements java.io.Serializable {


     private int usuariosIdUsuario;
     private Usuarios usuarios;
     private Date fechaServicio;
     private Date hora;
     private Set recorridosHasServicioses = new HashSet(0);

    public Recorridos() {
    }

	
    public Recorridos(Usuarios usuarios, Date fechaServicio, Date hora) {
        this.usuarios = usuarios;
        this.fechaServicio = fechaServicio;
        this.hora = hora;
    }
    public Recorridos(Usuarios usuarios, Date fechaServicio, Date hora, Set recorridosHasServicioses) {
       this.usuarios = usuarios;
       this.fechaServicio = fechaServicio;
       this.hora = hora;
       this.recorridosHasServicioses = recorridosHasServicioses;
    }
   
    public int getUsuariosIdUsuario() {
        return this.usuariosIdUsuario;
    }
    
    public void setUsuariosIdUsuario(int usuariosIdUsuario) {
        this.usuariosIdUsuario = usuariosIdUsuario;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getFechaServicio() {
        return this.fechaServicio;
    }
    
    public void setFechaServicio(Date fechaServicio) {
        this.fechaServicio = fechaServicio;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public Set getRecorridosHasServicioses() {
        return this.recorridosHasServicioses;
    }
    
    public void setRecorridosHasServicioses(Set recorridosHasServicioses) {
        this.recorridosHasServicioses = recorridosHasServicioses;
    }




}


