package modelo;
// Generated 6/10/2020 07:46:44 PM by Hibernate Tools 4.3.1



/**
 * RecorridosHasServicios generated by hbm2java
 */
public class RecorridosHasServicios  implements java.io.Serializable {


     private RecorridosHasServiciosId id;
     private Estaciones estacionesByEstacioneFin;
     private Estaciones estacionesByEstacionInicio;
     private Recorridos recorridos;
     private Servicios servicios;
     private String orden;

    public RecorridosHasServicios() {
    }

    public RecorridosHasServicios(RecorridosHasServiciosId id, Estaciones estacionesByEstacioneFin, Estaciones estacionesByEstacionInicio, Recorridos recorridos, Servicios servicios, String orden) {
       this.id = id;
       this.estacionesByEstacioneFin = estacionesByEstacioneFin;
       this.estacionesByEstacionInicio = estacionesByEstacionInicio;
       this.recorridos = recorridos;
       this.servicios = servicios;
       this.orden = orden;
    }
   
    public RecorridosHasServiciosId getId() {
        return this.id;
    }
    
    public void setId(RecorridosHasServiciosId id) {
        this.id = id;
    }
    public Estaciones getEstacionesByEstacioneFin() {
        return this.estacionesByEstacioneFin;
    }
    
    public void setEstacionesByEstacioneFin(Estaciones estacionesByEstacioneFin) {
        this.estacionesByEstacioneFin = estacionesByEstacioneFin;
    }
    public Estaciones getEstacionesByEstacionInicio() {
        return this.estacionesByEstacionInicio;
    }
    
    public void setEstacionesByEstacionInicio(Estaciones estacionesByEstacionInicio) {
        this.estacionesByEstacionInicio = estacionesByEstacionInicio;
    }
    public Recorridos getRecorridos() {
        return this.recorridos;
    }
    
    public void setRecorridos(Recorridos recorridos) {
        this.recorridos = recorridos;
    }
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }
    public String getOrden() {
        return this.orden;
    }
    
    public void setOrden(String orden) {
        this.orden = orden;
    }




}


