package modelo;
// Generated 6/10/2020 07:46:44 PM by Hibernate Tools 4.3.1



/**
 * Rutas generated by hbm2java
 */
public class Rutas  implements java.io.Serializable {


     private RutasId id;
     private Estaciones estaciones;
     private Servicios servicios;
     private byte origen;
     private byte destino;

    public Rutas() {
    }

    public Rutas(RutasId id, Estaciones estaciones, Servicios servicios, byte origen, byte destino) {
       this.id = id;
       this.estaciones = estaciones;
       this.servicios = servicios;
       this.origen = origen;
       this.destino = destino;
    }
   
    public RutasId getId() {
        return this.id;
    }
    
    public void setId(RutasId id) {
        this.id = id;
    }
    public Estaciones getEstaciones() {
        return this.estaciones;
    }
    
    public void setEstaciones(Estaciones estaciones) {
        this.estaciones = estaciones;
    }
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }
    public byte getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(byte origen) {
        this.origen = origen;
    }
    public byte getDestino() {
        return this.destino;
    }
    
    public void setDestino(byte destino) {
        this.destino = destino;
    }




}


