package modelo;
// Generated 6/10/2020 07:46:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Troncales generated by hbm2java
 */
public class Troncales  implements java.io.Serializable {


     private int idTroncal;
     private String nombreTroncal;
     private String letraTroncal;
     private Set zonases = new HashSet(0);

    public Troncales() {
    }

	
    public Troncales(int idTroncal, String nombreTroncal, String letraTroncal) {
        this.idTroncal = idTroncal;
        this.nombreTroncal = nombreTroncal;
        this.letraTroncal = letraTroncal;
    }
    public Troncales(int idTroncal, String nombreTroncal, String letraTroncal, Set zonases) {
       this.idTroncal = idTroncal;
       this.nombreTroncal = nombreTroncal;
       this.letraTroncal = letraTroncal;
       this.zonases = zonases;
    }
   
    public int getIdTroncal() {
        return this.idTroncal;
    }
    
    public void setIdTroncal(int idTroncal) {
        this.idTroncal = idTroncal;
    }
    public String getNombreTroncal() {
        return this.nombreTroncal;
    }
    
    public void setNombreTroncal(String nombreTroncal) {
        this.nombreTroncal = nombreTroncal;
    }
    public String getLetraTroncal() {
        return this.letraTroncal;
    }
    
    public void setLetraTroncal(String letraTroncal) {
        this.letraTroncal = letraTroncal;
    }
    public Set getZonases() {
        return this.zonases;
    }
    
    public void setZonases(Set zonases) {
        this.zonases = zonases;
    }




}


