package modelo;
// Generated 6/10/2020 07:46:44 PM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idUsuario;
     private String nombreUsuario;
     private String apellidoUsuario;
     private String numeroCelular;
     private String email;
     private Recorridos recorridos;

    public Usuarios() {
    }

	
    public Usuarios(int idUsuario, String nombreUsuario, String apellidoUsuario, String numeroCelular) {
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        this.apellidoUsuario = apellidoUsuario;
        this.numeroCelular = numeroCelular;
    }
    public Usuarios(int idUsuario, String nombreUsuario, String apellidoUsuario, String numeroCelular, String email, Recorridos recorridos) {
       this.idUsuario = idUsuario;
       this.nombreUsuario = nombreUsuario;
       this.apellidoUsuario = apellidoUsuario;
       this.numeroCelular = numeroCelular;
       this.email = email;
       this.recorridos = recorridos;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getApellidoUsuario() {
        return this.apellidoUsuario;
    }
    
    public void setApellidoUsuario(String apellidoUsuario) {
        this.apellidoUsuario = apellidoUsuario;
    }
    public String getNumeroCelular() {
        return this.numeroCelular;
    }
    
    public void setNumeroCelular(String numeroCelular) {
        this.numeroCelular = numeroCelular;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Recorridos getRecorridos() {
        return this.recorridos;
    }
    
    public void setRecorridos(Recorridos recorridos) {
        this.recorridos = recorridos;
    }




}


